# Generated by Django 6.0.7 on 2026-07-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=16, unique=True)),
                ('latest_status', models.CharField(blank=True, choices=[('passing', 'Passing'), ('failing', 'Failing')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_cnt', models.IntegerField()),
                ('data', models.TextField()),
                ('data_hex', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing')], max_length=10)),
                ('rx_info', models.JSONField(default=list)),
                ('tx_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='iot.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'f_cnt'), name='unique_device_fcnt')],
            },
        ),
    ]
